services:
  opencrypto:
    build: .
    restart: always

    # -----------------------------------------------------------
    # RIMUOVI O COMMENTA QUESTE RIGHE:
    # ports:
    #   - "127.0.0.1:8081:80"
    # -----------------------------------------------------------

    networks:
      - default
      - npm_network

networks:
  npm_network:
    name: npm-prod_default
    external: true
